spring:
  application:
    name: preferences-service
  cloud:
    config:
      discovery:
        enabled: false
        service-id: openwms-config
      enabled: false
      fail-fast: true # true means retry
      retry:
        max-attempts: 120
    discovery:
      enabled: false
  security:
    user:
      password: sa
      name: user
  jpa:
    show-sql: false
    open-in-view: false
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSZ
    serialization:
      fail_on_empty_beans: false

feign:
  httpclient:
    connection-timeout: 30000
    connection-timer-repeat: 30000
ribbon:
  connectTimeout: 30000
  ReadTimeout: 30000

owms:
  core:
    config:
      initial-properties: classpath:initial-preferences.xml
  eureka:
    url: http://user:sa@localhost:8761
    zone: ${owms.eureka.url}/eureka/
  srv:
    protocol: http
    hostname: localhost

server:
  port: ${PORT:8125}

eureka:
  client:
    instance-info-replication-interval-seconds: 10 # default is 30
    service-url:
      defaultZone: ${owms.eureka.zone}  # Must be camelCase
  instance:
    hostname: ${owms.srv.hostname}
    secure-port-enabled: false
    non-secure-port-enabled: true
    metadata-map:
      username: ${spring.security.user.name}
      password: ${spring.security.user.password}
      protocol: ${owms.srv.protocol}
      zone: ${owms.eureka.zone}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    rabbit:
      enabled: false

logging:
  file:
    name: BOOT-CORE-Preferences.log
    path: "/tmp/owms"

---
spring:
  config:
    activate:
      on-profile: ASYNCHRONOUS
  cloud:
    config:
      discovery:
        enabled: true
      enabled: true
      fail-fast: true # true means retry
    discovery:
      enabled: true

management:
  health:
    rabbit:
      enabled: true

---
spring:
  config:
    activate:
      on-profile: DISTRIBUTED
  cloud:
    config:
      discovery:
        enabled: true
      enabled: true
      fail-fast: true # true means retry
    discovery:
      enabled: true

---
spring:
  config:
    activate:
      on-profile: HEROKU
  main:
    banner-mode: "OFF"
  cloud:
    config:
      discovery:
        enabled: true
      enabled: true

owms:
  srv:
    protocol: https
    hostname: openwms-core-preferences.herokuapp.com

eureka:
  instance:
    secure-port-enabled: true
    non-secure-port-enabled: false
    statusPageUrl: ${owms.srv.protocol}://${owms.srv.hostname}:${server.port}/actuator/info
    healthCheckUrl: ${owms.srv.protocol}://${owms.srv.hostname}:${server.port}/actuator/health
    homePageUrl: ${owms.srv.protocol}://${owms.srv.hostname}:${server.port}/actuator/

---
spring:
  config:
    activate:
      on-profile: K8S
  rabbitmq:
    host: owms-broker
owms:
  eureka:
    url: http://user:sa@owms-services:8761
  srv:
    hostname: preferences-service

---
spring:
  config:
    activate:
      on-profile: TEST
  cloud:
    config:
      discovery:
        enabled: false
      enabled: false
      fail-fast: false
    service-registry:
      auto-registration:
        enabled: false
    discovery:
      enabled: false
  main:
    banner-mode: "off"
eureka:
  client:
    enabled: false
    refresh:
      enable: false
    serviceUrl:
      registerWithEureka: false

---
spring:
  config:
    activate:
      on-profile: TESTPG
  jpa:
    database: postgresql
    generate-ddl: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQL9Dialect
      hibernate.temp.use_jdbc_metadata_defaults: false
      hibernate.default_schema: public
    hibernate:
      ddl-auto: create
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql:testdb
    username: KARL
    password: KARL
